### ISSUE TITLE
Auto generate release via CI build

### ISSUE THREAD

**Issue by sneat** [danielbuechele/atemOSC#82]
It would be good to have Travis CI do the build automatically, including generating the draft release.

Initial discussion was in https://github.com/danielbuechele/atemOSC/pull/81

I had played around with trying to get it to work, but couldn't get Travis CI to make it past the `create-dmg 'atemOSC.app'` step, it would always fail there. I believe it's because `create-dmg` is exiting with a status of 1 due to it failing the code signing.

Here is the `.travis.yml` file that I was testing:

```yaml
os: osx
language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: compile
      install: npm install --global create-dmg
      script: create-dmg 'atemOSC.app' || true
      script: echo "$(find atemOSC-*.dmg)"
      script: find atemOSC-*.dmg
    - stage: deploy
      deploy:
        - provider: pages
          local_dir: website
          github_token: $GITHUB_TOKEN
          on:
            branch: master
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: atemOSC-*.dmg
          skip_cleanup: true
          on:
            tags: true
```

The suggestion is perhaps we can get Travis CI to do the code signing for us too (e.g. http://jviotti.com/2016/03/16/how-to-code-sign-os-x-electron-apps-in-travis-ci.html).
